source: ./source
plugins: ./source/_plugins
destination: ./site
markdown: rdiscount
future: false
paginate: 5
paginate_base: /
paginate_index: index.html

title: Oliver Joseph Ash
description: The journal of Oliver Joseph Ashâ€™s final year University project.
url: http://project.oliverash.me

navigation:
- text: Home
  url: http://oliverash.me/
- text: Final Year Project
  url: /
